name: Deployment
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - main
jobs:
  Deployment-With-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependecies
        run: npm install

      - name: Run Linter
        run: npm run eslint

      - name: Run unit tests
        run: npm run test

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests e2e
        run: npm run test:e2e