name: Deployment
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - opened

jobs:
  Avoid_reduncy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  Lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
      - name: Install dependecies
        run: pnpm install --no-frozen-lockfile

      - name: Run Linter
        run: pnpm run eslint

  Unit_Tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
      - name: Install dependecies
        run: pnpm install --no-frozen-lockfile

      - name: Run unit tests
        run: pnpm run test
  
  Build:
    needs: [Lint, Unit_Tests]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
      - name: Install dependecies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build
      
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  E2E_Tests:
    needs: [Build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
      - name: Install dependecies
        run: pnpm install --no-frozen-lockfile

      - name: Install playwright browsers
        run: pnpx playwright install --with-deps

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Run tests e2e
        run: pnpm run test:e2e

